name: Publish to NPM

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  id-token: write

# on:
#   workflow_run:
#     workflows: [QA]
#     branches: [develop]
#     types:
#       - completed

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v6
      - name: Use Node.js 18
        uses: actions/setup-node@v6
        with:
          node-version: '18.x'
          always-auth: true
      - name: Install Yarn
        run: npm install -g yarn

      - name: Update package.json version
        if: github.ref_name == 'develop'
        run: npm version preminor --no-git-tag-version --preid=dev-$(date -u +"%Y%m%d%H%M%S").$(git rev-parse --short HEAD)

      - name: Install dependencies
        run: yarn
      - name: Run tests
        run: yarn test
      - name: Build
        run: yarn build
      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmAuthToken $NPM_AUTH_TOKEN
          yarn config set npmAlwaysAuth true
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
        run: |
          npm config delete //registry.npmjs.org/:_authToken || true
          if [ "${{ github.ref_name }}" = "develop" ]; then
            yarn npm publish --provenance --access public --tag dev
          else
            yarn npm publish --provenance --access public
          fi
