name: QA

on:
  push:
    paths-ignore:
      - '.github/workflows/acceptance.yaml'
      - '.github/workflows/reward.yml'
      - '*.md'
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: the-ton-tech/toolchain/lint@v1.4.0
  build:
    name: Test & Build
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: the-ton-tech/toolchain/build@v1.4.0
