name: Security checks

on:
  pull_request:
    branches:
      - master
    paths:
      - .github/workflows/security.yml
      - .yarnrc.yml
      - package.json
      - yarn.lock
  push:
    branches:
      - master
    paths:
      - .github/workflows/security.yml
      - .yarnrc.yml
      - package.json
      - yarn.lock
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  security:
    name: Security checks
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Fetch Sources
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 22.x
          package-manager-cache: false

      - name: Check project packages for deprecated
        run: yarn npm audit --all --severity moderate

      - name: Check all packages for vulnerabilities
        run: yarn npm audit --all --recursive --severity high
